use_frameworks!

platform :ios, '11.0'

install! 'cocoapods', :deterministic_uuids => false

target 'RoxChatMobileWidget_Example' do
  pod 'RoxChatMobileWidget', :path => '../'
  pod 'RoxchatClientLibrary', :path => '../../mobile-sdk-ios'
  target 'RoxChatMobileWidget_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
        if target.name == "RoxChatMobileWidget"
            target.build_configurations.each do |config|
                config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
            end
        end
    end
end
